-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2023. Máj 02. 08:45
-- Kiszolgáló verziója: 10.4.24-MariaDB
-- PHP verzió: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `f1`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `kaszni`
--

CREATE TABLE `kaszni` (
  `id` int(11) NOT NULL,
  `leiras` varchar(255) NOT NULL,
  `kasznikomponens` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `price` int(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `kaszni`
--

INSERT INTO `kaszni` (`id`, `leiras`, `kasznikomponens`, `quantity`, `price`) VALUES
(1, 'The main structure of the car, which includes the cockpit, suspension, and power unit assembly', 'Chassis', 10, 2000000000),
(2, 'High-performance, turbocharged V6 engine with hybrid technology that recovers much of the energy from braking and exhaust gases', 'Power Unit', 12, 1500000000),
(3, 'The transmission that transfers power from the power unit to the rear wheels', 'Gearbox', 20, 700000),
(4, 'High-performance brake discs and calipers designed to withstand high temperatures and forces', 'Brakes', 10, 700000000),
(5, 'A complex system of dampers, springs, and linkages that allow the car to handle sharp turns and uneven surfaces at high speeds', 'Suspension', 10, 7000000),
(6, 'The design of the car\'s body, wings, and other components to optimize downforce and minimize drag', 'Aerodynamics', 10, 7000000),
(7, 'Specifically designed high-performance tires that provide grip and durability on the track', 'Tires', 50, 1100000),
(8, 'A highly precise, responsive steering system that allows the driver to make precise adjustments while driving at high speeds', 'Steering', 8, 37000000),
(9, 'A complex system of fuel tanks, pumps, and lines that deliver fuel to the power unit', 'Fuel System', 10, 112000000),
(10, 'A sophisticated network of sensors, data collection systems, and electronic controls that assist the driver and engineers in monitoring and optimizing performance', 'Electronics', 10, 149000000);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `motor`
--

CREATE TABLE `motor` (
  `id` int(11) NOT NULL,
  `leiras` varchar(255) NOT NULL,
  `motorkomponens` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `motor`
--

INSERT INTO `motor` (`id`, `leiras`, `motorkomponens`, `quantity`, `price`) VALUES
(1, 'The main component of the engine that houses the cylinders and the pistons.', 'Cylinder Block', 6, 373000000),
(2, 'The component that moves up and down in the cylinders and generates power.', 'Pistons', 10, 22000000),
(3, 'The rods that connect the pistons to the crankshaft and transmit the power generated by the engine.', 'Connecting rods', 8, 1000000),
(4, 'The component that converts the up-and-down motion of the pistons into a rotary motion that can be transmitted to the gearbox.', 'Crankshaft', 8, 11000000),
(5, 'The shafts that operate the valves, which control the intake and exhaust of air and fuel in the engine.', 'Camshafts', 6, 7000000),
(6, 'The components that allow air and fuel into the engine and exhaust gases out of the engine.', 'Valves', 20, 3000000),
(7, 'A device that compresses air to increase the power output of the engine.', 'Turbocharger', 6, 1000000000),
(8, 'A component that cools the compressed air from the turbocharger before it enters the engine.', 'Intercooler', 4, 7000000),
(9, 'The components that inject fuel into the engine\'s cylinders.', 'Fuel injectors', 12, 1100000),
(10, 'A system that ignites the air and fuel mixture in the cylinders to produce power.', 'Ignition system', 4, 13000000),
(11, 'A system that removes exhaust gases from the engine.', 'Exhaust system', 6, 7000000),
(12, 'Various sensors and control units that monitor and optimize the engine\'s performance.', 'Sensors and control units', 8, 5000000);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `pilotak`
--

CREATE TABLE `pilotak` (
  `nev` varchar(255) NOT NULL,
  `kor` int(11) NOT NULL,
  `nemzetiseg` varchar(255) NOT NULL,
  `csapat` varchar(255) NOT NULL,
  `szerzettpontok` int(11) NOT NULL,
  `kategoria` varchar(255) NOT NULL,
  `helyezes` int(11) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `pilotak`
--

INSERT INTO `pilotak` (`nev`, `kor`, `nemzetiseg`, `csapat`, `szerzettpontok`, `kategoria`, `helyezes`, `id`) VALUES
('Felipe Drugovich', 22, 'Brazilian', 'MP Motorsport', 265, 'Formula2', 1, 1),
('Theo Pourchaire', 19, 'France', 'ART Grand Prix', 164, 'Formula2', 2, 2),
('Liam Lawson', 21, 'New Zealander', 'Carlin', 149, 'Formula2', 3, 3),
('Logan Sargeant', 22, 'USA', 'Carlin', 148, 'Formula2', 4, 4),
('Ayumu Iwasa', 21, 'Japan', 'DAMS', 139, 'Formula2', 5, 5),
('Jack Doohan', 20, 'Australia', 'Virtuosi Racing', 128, 'Formula2', 6, 6),
('Jehan Daruvala', 24, 'India', 'Prema Racing', 126, 'Formula2', 7, 7),
('Enzo Fittipaldi', 21, 'Brasil', 'Charouz Racing System', 126, 'Formula2', 7, 8),
('Frederik Vesti', 21, 'Denmark', 'ART Grand Prix', 117, 'Formula2', 8, 9),
('Dennis Hauger', 19, 'Norway', 'Prema Racing', 115, 'Formula2', 9, 10),
('Juri Vips', 22, 'Estonia', 'Hitech Grand Prix', 114, 'Formula2', 10, 11),
('Richard Verschoor', 22, 'Netherland', 'Trident', 103, 'Formula2', 11, 12),
('Marcus Armstrong', 22, 'Australia', 'Hitech Grand Prix', 93, 'Formula2', 12, 13),
('Clement Novalak', 22, 'France', 'MP Motorsport', 40, 'Formula2', 13, 14),
('Ralph Boschung', 25, 'Switzerland', 'Campos Racing', 40, 'Formula2', 13, 15),
('Jake Hughes', 28, 'United Kingdom', 'Van Amersfoort Racing', 26, 'Formula2', 14, 16),
('Amaury Cordeel', 20, 'Belgium', 'Van Amersfoort Racing', 26, 'Formula2', 14, 17),
('David Beckmann', 22, 'Germany', 'Van Amersfoort Racing', 25, 'Formula2', 15, 18),
('Roy Nissany', 28, 'Israel', 'DAMS', 20, 'Formula2', 16, 19),
('Roberto Merhi', 31, 'Spain', 'Campos Racing', 15, 'Formula2', 17, 20),
('Olivér Caldwell', 20, 'United Kingdom', 'Campos Racing', 12, 'Formula2', 18, 21),
('Marino Sato', 23, 'Japan', 'Virtuosi', 6, 'Formula2', 19, 22),
('Calan Williams', 22, 'Australia', 'Trident', 5, 'Formula2', 20, 23),
('Cem Bolukbasi', 25, 'Turkey', 'Charouz Racing System', 0, 'Formula2', 21, 24),
('Luca Ghiotto', 28, 'Italy', 'Hitech Grand Prix', 0, 'Formula2', 21, 25),
('Zane Maloney', 19, 'Barbados', 'Trident', 0, 'Formula2', 21, 26),
('Juan Manuel Correa', 23, 'USA', 'ART Grand Prix', 0, 'Formula2', 21, 27),
('Tatiana Calderon', 29, 'Columbia', 'Charouz Racing System', 0, 'Formula2', 21, 28),
('Lirim Zendeli', 23, 'Germany', 'MP Motorsport', 0, 'Formula2', 21, 29),
('Victor Martins', 21, 'France', 'ART Grand Prix', 139, 'Formula3', 1, 30),
('Oliver Bearman', 19, 'United Kingdom', 'Prema Racing', 132, 'Formula3', 2, 31),
('Isack Hadjar', 18, 'France', 'Hitech Grand Prix', 123, 'Formula3', 3, 32),
('Roman Stanek', 19, 'Czech Republic', 'Trident', 117, 'Formula3', 4, 33),
('Arthur Leclerc', 22, 'Monaco', 'Prema Racing', 114, 'Formula3', 5, 34),
('Jak Crawford', 17, 'USA', 'Prema Racing', 109, 'Formula3', 6, 35),
('Caio Collet', 20, 'Brasil', 'MP Motorsport', 88, 'Formula3', 7, 36),
('Franco Colapinto', 19, 'Argentina', 'Van Amersfoort Racing', 76, 'Formula3', 8, 37),
('Alekszandr Szmoljar', 21, 'Russian', 'MP Motorsport', 76, 'Formula3', 8, 38),
('Zak OSullivan', 18, 'United Kingdom', 'Carlin', 54, 'Formula3', 9, 39),
('Jonny Edgar', 19, 'United Kingdom', 'Trident', 46, 'Formula3', 10, 40),
('Kush Maini', 22, 'India', 'MP Motorsport', 31, 'Formula3', 11, 41),
('Grégoire Saucy', 23, 'Switzerland', 'ART Grand Prix', 30, 'Formula3', 12, 42),
('David Vidales', 20, 'Spain', 'Campos Racing', 29, 'Formula3', 13, 43),
('Kaylen Federick', 20, 'USA', 'Hitech Grand Prix', 27, 'Formula3', 14, 44),
('William Alatalo', 20, 'Finland', 'Jenzer Motorsport', 24, 'Formula3', 15, 45),
('Oliver Goathe', 18, 'Monaco', 'Campos Racing', 15, 'Formula3', 16, 46),
('Reece Ushijima', 20, 'United Kingdom', 'Van Amersfoort Racing', 13, 'Formula3', 17, 47),
('Sebastian Montoya', 17, 'Columbia', 'Campos Racing', 7, 'Formula3', 18, 48),
('Oliver Rasmussen', 2, 'Denmark', 'Trident', 4, 'Formula3', 19, 49),
('Brad Benavides', 21, 'USA', 'Carlin', 3, 'Formula3', 20, 50),
('Rafael Villagómez', 21, 'Mexico', 'Van Amersfoort Racing', 2, 'Formula3', 21, 51),
('Pepe Martí', 17, 'Spain', 'Campos Racing', 2, 'Formula3', 21, 52),
('Ido Cohen', 21, 'Israel', 'Jenzer Motorsport', 2, 'Formula3', 21, 53),
('Francesco Pizzi', 18, 'Italy', 'Charouz Racing System', 1, 'Formula3', 22, 54),
('David Schumacher', 21, 'Germany', 'Charouz Racing System', 0, 'Formula3', 23, 55),
('Ayrton Simmons', 21, 'United Kingdom', 'Charouz Racing System', 0, 'Formula3', 23, 56),
('Tóth László', 22, 'Hungary', 'Charouz Racing System', 0, 'Formula3', 23, 57),
('Christian Mansell', 18, 'Australia', 'Charouz Racing System', 0, 'Formula3', 23, 58),
('Alessandro Famularo', 20, 'Italy', 'Charouz Racing System', 0, 'Formula3', 23, 59),
('Zdenek Chovanec', 18, 'Portugal', 'Charouz Racing System', 0, 'Formula3', 23, 60),
('Federico Malvestiti', 22, 'Italy', 'Jenzer Motorsport', 0, 'Formula3', 23, 61),
('Niko Kari', 23, 'Finland', 'Jenzer Motorsport', 0, 'Formula3', 23, 62),
('Nazim Azman', 21, 'Malaysia', 'Hitech Grand Prix', 0, 'Formula3', 23, 63),
('Hunter Yeany', 17, 'USA', 'Campos Racing', 0, 'Formula3', 23, 64),
('Enzo Trulli', 17, 'Italy', 'Carlin', 0, 'Formula3', 23, 65),
('Filip Ugran', 20, 'Romania', 'MP Motorsport', 0, 'Formula3', 23, 66);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `shop`
--

CREATE TABLE `shop` (
  `id` int(11) NOT NULL,
  `type` varchar(255) NOT NULL,
  `team` varchar(255) NOT NULL,
  `size` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `price` int(11) NOT NULL,
  `quantity` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `shop`
--

INSERT INTO `shop` (`id`, `type`, `team`, `size`, `color`, `price`, `quantity`) VALUES
(1, 'T-shirt', 'Red-Bull', 'XS', 'Blue', 20000, 20),
(2, 'T-shirt', 'Red-Bull', 'S', 'Blue', 20000, 20),
(3, 'T-shirt', 'Red-Bull', 'M', 'Blue', 22000, 20),
(4, 'T-shirt', 'Red-Bull', 'L', 'Blue', 25000, 20),
(5, 'T-shirt', 'Red-Bull', 'XL', 'Blue', 28000, 20),
(6, 'T-shirt', 'Red-Bull', 'XS', 'White', 20000, 20),
(7, 'T-shirt', 'Red-Bull', 'S', 'White', 20000, 20),
(8, 'T-shirt', 'Red-Bull', 'M', 'White', 22000, 20),
(9, 'T-shirt', 'Red-Bull', 'L', 'White', 25000, 20),
(10, 'T-shirt', 'Red-Bull', 'XL', 'White', 28000, 20),
(11, 'T-shirt', 'Red-Bull', 'XS', 'Orange', 20000, 20),
(12, 'T-shirt', 'Red-Bull', 'S', 'Orange', 20000, 20),
(13, 'T-shirt', 'Red-Bull', 'M', 'Orange', 22000, 20),
(14, 'T-shirt', 'Red-Bull', 'L', 'Orange', 25000, 20),
(15, 'T-shirt', 'Red-Bull', 'XL', 'Orange', 28000, 20),
(16, 'T-shirt', 'Ferrari', 'XS', 'Red', 20000, 20),
(17, 'T-shirt', 'Ferrari', 'S', 'Red', 20000, 20),
(18, 'T-shirt', 'Ferrari', 'M', 'Red', 22000, 20),
(19, 'T-shirt', 'Ferrari', 'L', 'Red', 25000, 20),
(20, 'T-shirt', 'Ferrari', 'XL', 'Red', 28000, 20),
(21, 'T-shirt', 'Ferrari', 'XS', 'Yellow', 20000, 20),
(22, 'T-shirt', 'Ferrari', 'S', 'Yellow', 20000, 20),
(23, 'T-shirt', 'Ferrari', 'M', 'Yellow', 22000, 20),
(24, 'T-shirt', 'Ferrari', 'L', 'Yellow', 25000, 20),
(25, 'T-shirt', 'Ferrari', 'XL', 'Yellow', 28000, 20),
(31, 'T-shirt', 'Mercedes', 'XS', 'White', 20000, 20),
(32, 'T-shirt', 'Mercedes', 'S', 'White', 20000, 20),
(33, 'T-shirt', 'Mercedes', 'M', 'White', 22000, 20),
(34, 'T-shirt', 'Mercedes', 'L', 'White', 25000, 20),
(35, 'T-shirt', 'Mercedes', 'XL', 'White', 28000, 20),
(36, 'T-shirt', 'Mercedes', 'XS', 'Black', 20000, 20),
(37, 'T-shirt', 'Mercedes', 'S', 'Black', 20000, 20),
(38, 'T-shirt', 'Mercedes', 'M', 'Black', 22000, 20),
(39, 'T-shirt', 'Mercedes', 'L', 'Black', 25000, 20),
(40, 'T-shirt', 'Mercedes', 'XL', 'Black', 28000, 20),
(41, 'T-shirt', 'Mclaren', 'XS', 'Orange', 20000, 20),
(42, 'T-shirt', 'Mclaren', 'S', 'Orange', 20000, 20),
(43, 'T-shirt', 'Mclaren', 'M', 'Orange', 22000, 20),
(44, 'T-shirt', 'Mclaren', 'L', 'Orange', 25000, 20),
(45, 'T-shirt', 'Mclaren', 'XL', 'Orange', 28000, 20),
(46, 'T-shirt', 'Mclaren', 'XS', 'Black', 20000, 20),
(47, 'T-shirt', 'Mclaren', 'S', 'Black', 20000, 20),
(48, 'T-shirt', 'Mclaren', 'M', 'Black', 22000, 20),
(49, 'T-shirt', 'Mclaren', 'L', 'Black', 25000, 20),
(50, 'T-shirt', 'Mclaren', 'XL', 'Black', 28000, 20),
(51, 'T-shirt', 'Aston-Martin', 'XS', 'Green', 20000, 20),
(52, 'T-shirt', 'Aston-Martin', 'S', 'Green', 20000, 20),
(53, 'T-shirt', 'Aston-Martin', 'M', 'Green', 22000, 20),
(54, 'T-shirt', 'Aston-Martin', 'L', 'Green', 25000, 20),
(55, 'T-shirt', 'Aston-Martin', 'XL', 'Green', 28000, 20),
(56, 'T-shirt', 'Alfa-Romeo', 'XS', 'Black', 20000, 20),
(57, 'T-shirt', 'Alfa-Romeo', 'S', 'Black', 20000, 20),
(58, 'T-shirt', 'Alfa-Romeo', 'M', 'Black', 22000, 20),
(59, 'T-shirt', 'Alfa-Romeo', 'L', 'Black', 25000, 20),
(60, 'T-shirt', 'Alfa-Romeo', 'XL', 'Black', 28000, 20),
(61, 'T-shirt', 'Alpine', 'XS', 'Black', 20000, 20),
(62, 'T-shirt', 'Alpine', 'S', 'Black', 20000, 20),
(63, 'T-shirt', 'Alpine', 'M', 'Black', 22000, 20),
(64, 'T-shirt', 'Alpine', 'L', 'Black', 25000, 20),
(65, 'T-shirt', 'Alpine', 'XL', 'Black', 28000, 20),
(66, 'T-shirt', 'Alpine', 'XS', 'White', 20000, 20),
(67, 'T-shirt', 'Alpine', 'S', 'White', 20000, 20),
(68, 'T-shirt', 'Alpine', 'M', 'White', 22000, 20),
(69, 'T-shirt', 'Alpine', 'L', 'White', 25000, 20),
(70, 'T-shirt', 'Alpine', 'XL', 'White', 28000, 20),
(71, 'T-shirt', 'Alpine', 'XS', 'Blue', 20000, 20),
(72, 'T-shirt', 'Alpine', 'S', 'Blue', 20000, 20),
(73, 'T-shirt', 'Alpine', 'M', 'Blue', 22000, 20),
(74, 'T-shirt', 'Alpine', 'L', 'Blue', 25000, 20),
(75, 'T-shirt', 'Alpine', 'XL', 'Blue', 28000, 20),
(76, 'T-shirt', 'Alpha-Tauri', 'XS', 'Black', 20000, 20),
(78, 'T-shirt', 'Alpha-Tauri', 'S', 'Black', 20000, 20),
(80, 'T-shirt', 'Alpha-Tauri', 'M', 'Black', 22000, 20),
(83, 'T-shirt', 'Alpha-Tauri', 'L', 'Black', 25000, 20),
(84, 'T-shirt', 'Alpha-Tauri', 'XL', 'Black', 28000, 20),
(86, 'T-shirt', 'Alpha-Tauri', 'XS', 'White', 20000, 20),
(87, 'T-shirt', 'Alpha-Tauri', 'S', 'White', 20000, 20),
(88, 'T-shirt', 'Alpha-Tauri', 'M', 'White', 22000, 20),
(89, 'T-shirt', 'Alpha-Tauri', 'L', 'White', 25000, 20),
(90, 'T-shirt', 'Alpha-Tauri', 'XL', 'White', 28000, 20),
(91, 'T-shirt', 'Williams', 'XS', 'Blue', 20000, 20),
(92, 'T-shirt', 'Williams', 'S', 'Blue', 20000, 20),
(93, 'T-shirt', 'Williams', 'M', 'Blue', 22000, 20),
(94, 'T-shirt', 'Williams', 'L', 'Blue', 25000, 20),
(95, 'T-shirt', 'Williams', 'XL', 'Blue', 28000, 20),
(96, 'T-shirt', 'Haas', 'XS', 'Black', 20000, 20),
(97, 'T-shirt', 'Haas', 'S', 'Black', 20000, 20),
(98, 'T-shirt', 'Haas', 'M', 'Black', 22000, 20),
(99, 'T-shirt', 'Haas', 'L', 'Black', 25000, 20),
(100, 'T-shirt', 'Haas', 'XL', 'Black', 28000, 20),
(101, 'T-shirt', 'Haas', 'XS', 'White', 20000, 20),
(102, 'T-shirt', 'Haas', 'S', 'White', 20000, 20),
(103, 'T-shirt', 'Haas', 'M', 'White', 22000, 20),
(104, 'T-shirt', 'Haas', 'L', 'White', 25000, 20),
(105, 'T-shirt', 'Haas', 'XL', 'White', 28000, 20),
(106, 'Cap', 'Red-Bull', 'XS', 'Blue', 17000, 20),
(107, 'Cap', 'Red-Bull', 'S', 'Blue', 17000, 20),
(108, 'Cap', 'Red-Bull', 'M', 'Blue', 17000, 20),
(109, 'Cap', 'Red-Bull', 'L', 'Blue', 17000, 20),
(110, 'Cap', 'Red-Bull', 'XL', 'Blue', 17000, 20),
(111, 'Cap', 'Red-Bull', 'XS', 'White', 17000, 20),
(112, 'Cap', 'Red-Bull', 'S', 'White', 17000, 20),
(113, 'Cap', 'Red-Bull', 'M', 'White', 17000, 20),
(114, 'Cap', 'Red-Bull', 'L', 'White', 17000, 20),
(115, 'Cap', 'Red-Bull', 'XL', 'White', 17000, 20),
(116, 'Cap', 'Red-Bull', 'XS', 'Orange', 17000, 20),
(117, 'Cap', 'Red-Bull', 'S', 'Orange', 17000, 20),
(118, 'Cap', 'Red-Bull', 'M', 'Orange', 17000, 20),
(119, 'Cap', 'Red-Bull', 'L', 'Orange', 17000, 20),
(120, 'Cap', 'Red-Bull', 'XL', 'Orange', 17000, 20),
(121, 'Cap', 'Ferrari', 'XS', 'Red', 17000, 20),
(122, 'Cap', 'Ferrari', 'S', 'Red', 17000, 20),
(123, 'Cap', 'Ferrari', 'M', 'Red', 17000, 20),
(124, 'Cap', 'Ferrari', 'L', 'Red', 17000, 20),
(125, 'Cap', 'Ferrari', 'XL', 'Red', 17000, 20),
(126, 'Cap', 'Ferrari', 'XS', 'Black', 17000, 20),
(127, 'Cap', 'Ferrari', 'S', 'Black', 17000, 20),
(128, 'Cap', 'Ferrari', 'M', 'Black', 17000, 20),
(129, 'Cap', 'Ferrari', 'L', 'Black', 17000, 20),
(130, 'Cap', 'Ferrari', 'XL', 'Black', 17000, 20),
(131, 'Cap', 'Ferrari', 'XS', 'White', 17000, 20),
(132, 'Cap', 'Ferrari', 'S', 'White', 17000, 20),
(133, 'Cap', 'Ferrari', 'M', 'White', 17000, 20),
(134, 'Cap', 'Ferrari', 'L', 'White', 17000, 20),
(135, 'Cap', 'Ferrari', 'XL', 'White', 17000, 20),
(136, 'Cap', 'Mercedes', 'XS', 'Black', 17000, 20),
(137, 'Cap', 'Mercedes', 'S', 'Black', 17000, 20),
(138, 'Cap', 'Mercedes', 'M', 'Black', 17000, 20),
(139, 'Cap', 'Mercedes', 'L', 'Black', 17000, 20),
(140, 'Cap', 'Mercedes', 'XL', 'Black', 17000, 20),
(141, 'Cap', 'Mercedes', 'XS', 'White', 17000, 20),
(142, 'Cap', 'Mercedes', 'S', 'White', 17000, 20),
(143, 'Cap', 'Mercedes', 'M', 'White', 17000, 20),
(144, 'Cap', 'Mercedes', 'L', 'White', 17000, 20),
(145, 'Cap', 'Mercedes', 'XL', 'White', 17000, 20),
(146, 'Cap', 'Mclaren', 'XS', 'Orange', 17000, 20),
(147, 'Cap', 'Mclaren', 'S', 'Orange', 17000, 20),
(148, 'Cap', 'Mclaren', 'M', 'Orange', 17000, 20),
(149, 'Cap', 'Mclaren', 'L', 'Orange', 17000, 20),
(150, 'Cap', 'Mclaren', 'XL', 'Orange', 17000, 20),
(151, 'Cap', 'Mclaren', 'XS', 'Black', 17000, 20),
(152, 'Cap', 'Mclaren', 'S', 'Black', 17000, 20),
(153, 'Cap', 'Mclaren', 'M', 'Black', 17000, 20),
(154, 'Cap', 'Mclaren', 'L', 'Black', 17000, 20),
(155, 'Cap', 'Mclaren', 'XL', 'Black', 17000, 20),
(156, 'Cap', 'Aston-Martin', 'XS', 'Green', 17000, 20),
(157, 'Cap', 'Aston-Martin', 'S', 'Green', 17000, 20),
(158, 'Cap', 'Aston-Martin', 'M', 'Green', 17000, 20),
(159, 'Cap', 'Aston-Martin', 'L', 'Green', 17000, 20),
(160, 'Cap', 'Aston-Martin', 'XL', 'Green', 17000, 20),
(161, 'Cap', 'Alfa-Romeo', 'XS', 'Black', 17000, 20),
(162, 'Cap', 'Alfa-Romeo', 'S', 'Black', 17000, 20),
(163, 'Cap', 'Alfa-Romeo', 'M', 'Black', 17000, 20),
(164, 'Cap', 'Alfa-Romeo', 'L', 'Black', 17000, 20),
(165, 'Cap', 'Alfa-Romeo', 'XL', 'Black', 17000, 20),
(166, 'Cap', 'Alpine', 'XS', 'Black', 17000, 20),
(167, 'Cap', 'Alpine', 'S', 'Black', 17000, 20),
(168, 'Cap', 'Alpine', 'M', 'Black', 17000, 20),
(169, 'Cap', 'Alpine', 'L', 'Black', 17000, 20),
(170, 'Cap', 'Alpine', 'XL', 'Black', 17000, 20),
(171, 'Cap', 'Alpine', 'XS', 'White', 17000, 20),
(172, 'Cap', 'Alpine', 'S', 'White', 17000, 20),
(173, 'Cap', 'Alpine', 'M', 'White', 17000, 20),
(174, 'Cap', 'Alpine', 'L', 'White', 17000, 20),
(175, 'Cap', 'Alpine', 'XL', 'White', 17000, 20),
(176, 'Cap', 'Alpine', 'XS', 'Blue', 17000, 20),
(177, 'Cap', 'Alpine', 'S', 'Blue', 17000, 20),
(178, 'Cap', 'Alpine', 'M', 'Blue', 17000, 20),
(179, 'Cap', 'Alpine', 'L', 'Blue', 17000, 20),
(180, 'Cap', 'Alpine', 'XL', 'Blue', 17000, 20),
(181, 'Cap', 'Alpha-Tauri', 'XS', 'Black', 17000, 20),
(182, 'Cap', 'Alpha-Tauri', 'S', 'Black', 17000, 20),
(183, 'Cap', 'Alpha-Tauri', 'M', 'Black', 17000, 20),
(184, 'Cap', 'Alpha-Tauri', 'L', 'Black', 17000, 20),
(185, 'Cap', 'Alpha-Tauri', 'XL', 'Black', 17000, 20),
(186, 'Cap', 'Alpha-Tauri', 'XS', 'White', 17000, 20),
(187, 'Cap', 'Alpha-Tauri', 'S', 'White', 17000, 20),
(188, 'Cap', 'Alpha-Tauri', 'M', 'White', 17000, 20),
(189, 'Cap', 'Alpha-Tauri', 'L', 'White', 17000, 20),
(190, 'Cap', 'Alpha-Tauri', 'XL', 'White', 17000, 20),
(191, 'Cap', 'Williams', 'XS', 'Blue', 17000, 20),
(192, 'Cap', 'Williams', 'S', 'Blue', 17000, 20),
(193, 'Cap', 'Williams', 'M', 'Blue', 17000, 20),
(194, 'Cap', 'Williams', 'L', 'Blue', 17000, 20),
(195, 'Cap', 'Williams', 'XL', 'Blue', 17000, 20),
(196, 'Cap', 'Haas', 'XS', 'Black', 17000, 20),
(197, 'Cap', 'Haas', 'S', 'Black', 17000, 20),
(198, 'Cap', 'Haas', 'M', 'Black', 17000, 20),
(199, 'Cap', 'Haas', 'L', 'Black', 17000, 20),
(200, 'Cap', 'Haas', 'XL', 'Black', 17000, 20),
(201, 'Cap', 'Haas', 'XS', 'White', 17000, 20),
(202, 'Cap', 'Haas', 'S', 'White', 17000, 20),
(203, 'Cap', 'Haas', 'M', 'White', 17000, 20),
(204, 'Cap', 'Haas', 'L', 'White', 17000, 20),
(205, 'Cap', 'Haas', 'XL', 'White', 17000, 20),
(206, 'Hoodie', 'Red-Bull', 'XS', 'Blue', 30000, 20),
(207, 'Hoodie', 'Red-Bull', 'S', 'Blue', 32000, 20),
(208, 'Hoodie', 'Red-Bull', 'M', 'Blue', 34000, 20),
(209, 'Hoodie', 'Red-Bull', 'L', 'Blue', 36000, 20),
(210, 'Hoodie', 'Red-Bull', 'XL', 'Blue', 38000, 20),
(211, 'Hoodie', 'Red-Bull', 'XS', 'White', 30000, 20),
(212, 'Hoodie', 'Red-Bull', 'S', 'White', 32000, 20),
(213, 'Hoodie', 'Red-Bull', 'M', 'White', 34000, 20),
(214, 'Hoodie', 'Red-Bull', 'L', 'White', 36000, 20),
(215, 'Hoodie', 'Red-Bull', 'XL', 'White', 38000, 20),
(216, 'Hoodie', 'Red-Bull', 'XS', 'Orange', 30000, 20),
(217, 'Hoodie', 'Red-Bull', 'S', 'Orange', 32000, 20),
(218, 'Hoodie', 'Red-Bull', 'M', 'Orange', 34000, 20),
(219, 'Hoodie', 'Red-Bull', 'L', 'Orange', 36000, 20),
(220, 'Hoodie', 'Red-Bull', 'XL', 'Orange', 38000, 20),
(221, 'Hoodie', 'Ferrari', 'XS', 'Red', 30000, 20),
(222, 'Hoodie', 'Ferrari', 'S', 'Red', 32000, 20),
(223, 'Hoodie', 'Ferrari', 'M', 'Red', 34000, 20),
(224, 'Hoodie', 'Ferrari', 'L', 'Red', 36000, 20),
(225, 'Hoodie', 'Ferrari', 'XL', 'Red', 38000, 20),
(226, 'Hoodie', 'Ferrari', 'XS', 'Yellow', 30000, 20),
(227, 'Hoodie', 'Ferrari', 'S', 'Yellow', 32000, 20),
(228, 'Hoodie', 'Ferrari', 'M', 'Yellow', 34000, 20),
(229, 'Hoodie', 'Ferrari', 'L', 'Yellow', 36000, 20),
(230, 'Hoodie', 'Ferrari', 'XL', 'Yellow', 38000, 20),
(231, 'Hoodie', 'Mercedes', 'XS', 'White', 30000, 20),
(232, 'Hoodie', 'Mercedes', 'S', 'White', 32000, 20),
(233, 'Hoodie', 'Mercedes', 'M', 'White', 34000, 20),
(234, 'Hoodie', 'Mercedes', 'L', 'White', 36000, 20),
(235, 'Hoodie', 'Mercedes', 'XL', 'White', 38000, 20),
(236, 'Hoodie', 'Mercedes', 'XS', 'Black', 30000, 20),
(237, 'Hoodie', 'Mercedes', 'S', 'Black', 32000, 20),
(238, 'Hoodie', 'Mercedes', 'M', 'Black', 34000, 20),
(239, 'Hoodie', 'Mercedes', 'L', 'Black', 36000, 20),
(240, 'Hoodie', 'Mercedes', 'XL', 'Black', 38000, 20),
(241, 'Hoodie', 'Mclaren', 'XS', 'Orange', 30000, 20),
(242, 'Hoodie', 'Mclaren', 'S', 'Orange', 32000, 20),
(243, 'Hoodie', 'Mclaren', 'M', 'Orange', 34000, 20),
(244, 'Hoodie', 'Mclaren', 'L', 'Orange', 36000, 20),
(245, 'Hoodie', 'Mclaren', 'XL', 'Orange', 38000, 20),
(246, 'Hoodie', 'Aston-Martin', 'XS', 'Green', 30000, 20),
(247, 'Hoodie', 'Aston-Martin', 'S', 'Green', 32000, 20),
(248, 'Hoodie', 'Aston-Martin', 'M', 'Green', 34000, 20),
(249, 'Hoodie', 'Aston-Martin', 'L', 'Green', 36000, 20),
(250, 'Hoodie', 'Aston-Martin', 'XL', 'Green', 38000, 20),
(251, 'Hoodie', 'Alfa-Romeo', 'XS', 'Black', 30000, 20),
(252, 'Hoodie', 'Alfa-Romeo', 'S', 'Black', 32000, 20),
(253, 'Hoodie', 'Alfa-Romeo', 'M', 'Black', 34000, 20),
(254, 'Hoodie', 'Alfa-Romeo', 'L', 'Black', 36000, 20),
(255, 'Hoodie', 'Alfa-Romeo', 'XL', 'Black', 38000, 20),
(256, 'Hoodie', 'Alpine', 'XS', 'Black', 30000, 20),
(257, 'Hoodie', 'Alpine', 'S', 'Black', 32000, 20),
(258, 'Hoodie', 'Alpine', 'M', 'Black', 34000, 20),
(259, 'Hoodie', 'Alpine', 'L', 'Black', 36000, 20),
(260, 'Hoodie', 'Alpine', 'XL', 'Black', 38000, 20),
(261, 'Hoodie', 'Alpine', 'XS', 'Blue', 30000, 20),
(262, 'Hoodie', 'Alpine', 'S', 'Blue', 32000, 20),
(263, 'Hoodie', 'Alpine', 'M', 'Blue', 34000, 20),
(264, 'Hoodie', 'Alpine', 'L', 'Blue', 36000, 20),
(265, 'Hoodie', 'Alpine', 'XL', 'Blue', 38000, 20),
(266, 'Hoodie', 'Alpha-Tauri', 'XS', 'Black', 30000, 20),
(267, 'Hoodie', 'Alpha-Tauri', 'S', 'Black', 32000, 20),
(268, 'Hoodie', 'Alpha-Tauri', 'M', 'Black', 34000, 20),
(269, 'Hoodie', 'Alpha-Tauri', 'L', 'Black', 36000, 20),
(270, 'Hoodie', 'Alpha-Tauri', 'XL', 'Black', 38000, 20),
(271, 'Hoodie', 'Williams', 'XS', 'Black', 30000, 20),
(272, 'Hoodie', 'Williams', 'S', 'Black', 32000, 20),
(273, 'Hoodie', 'Williams', 'M', 'Black', 34000, 20),
(274, 'Hoodie', 'Williams', 'L', 'Black', 36000, 20),
(275, 'Hoodie', 'Williams', 'XL', 'Black', 38000, 20),
(276, 'Hoodie', 'Williams', 'XS', 'Blue', 30000, 20),
(277, 'Hoodie', 'Williams', 'S', 'Blue', 32000, 20),
(278, 'Hoodie', 'Williams', 'M', 'Blue', 34000, 20),
(279, 'Hoodie', 'Williams', 'L', 'Blue', 36000, 20),
(280, 'Hoodie', 'Williams', 'XL', 'Blue', 38000, 20),
(281, 'Hoodie', 'Haas', 'XS', 'Black', 30000, 20),
(282, 'Hoodie', 'Haas', 'S', 'Black', 32000, 20),
(283, 'Hoodie', 'Haas', 'M', 'Black', 34000, 20),
(284, 'Hoodie', 'Haas', 'L', 'Black', 36000, 20),
(285, 'Hoodie', 'Haas', 'XL', 'Black', 38000, 20),
(286, 'Hoodie', 'Haas', 'XS', 'Blue', 30000, 20),
(287, 'Hoodie', 'Haas', 'S', 'Blue', 32000, 20),
(288, 'Hoodie', 'Haas', 'M', 'Blue', 34000, 20),
(289, 'Hoodie', 'Haas', 'L', 'Blue', 36000, 20),
(290, 'Hoodie', 'Haas', 'XL', 'Blue', 38000, 20);

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `token`
--

CREATE TABLE `token` (
  `token` varchar(255) NOT NULL,
  `userId` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `vezerloegyseg`
--

CREATE TABLE `vezerloegyseg` (
  `id` int(11) NOT NULL,
  `leiras` varchar(255) NOT NULL,
  `vezerloegysegkomponens` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `vezerloegyseg`
--

INSERT INTO `vezerloegyseg` (`id`, `leiras`, `vezerloegysegkomponens`, `quantity`, `price`) VALUES
(1, 'The control center of the F1 car, responsible for controlling various systems of the car, such as the fuel mixture delivery to the combustion chamber, the gearbox control, and optimizing fuel and energy efficiency.', 'Universal Control Unit (ECU)', 4, 112000000),
(2, 'Usually mounted on the steering wheel, this panel allows the driver to regulate various parameters of the car\'s control unit', 'Control Panel', 10, 29000000),
(3, 'Cables and connectors that are connected to the control unit for transmission between different systems and sensors', 'Cables', 200, 370000),
(4, 'Various sensors that are connected to the control unit, allowing it to monitor different systems of the car, such as fuel and oil pressure, temperature, and wheel grip', 'Sensors', 1200, 750000);

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `kaszni`
--
ALTER TABLE `kaszni`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `motor`
--
ALTER TABLE `motor`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `pilotak`
--
ALTER TABLE `pilotak`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `shop`
--
ALTER TABLE `shop`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `token`
--
ALTER TABLE `token`
  ADD PRIMARY KEY (`token`),
  ADD KEY `FK_94f168faad896c0786646fa3d4a` (`userId`);

--
-- A tábla indexei `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `vezerloegyseg`
--
ALTER TABLE `vezerloegyseg`
  ADD PRIMARY KEY (`id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `kaszni`
--
ALTER TABLE `kaszni`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT a táblához `motor`
--
ALTER TABLE `motor`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--
-- AUTO_INCREMENT a táblához `pilotak`
--
ALTER TABLE `pilotak`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=71;

--
-- AUTO_INCREMENT a táblához `shop`
--
ALTER TABLE `shop`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=291;

--
-- AUTO_INCREMENT a táblához `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT a táblához `vezerloegyseg`
--
ALTER TABLE `vezerloegyseg`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Megkötések a kiírt táblákhoz
--

--
-- Megkötések a táblához `token`
--
ALTER TABLE `token`
  ADD CONSTRAINT `FK_94f168faad896c0786646fa3d4a` FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
