-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2023. Ápr 14. 08:38
-- Kiszolgáló verziója: 10.4.24-MariaDB
-- PHP verzió: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `f1`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `motor`
--

CREATE TABLE `motor` (
  `id` int(11) NOT NULL,
  `leiras` varchar(255) NOT NULL,
  `motorkomponensek` varchar(255) NOT NULL,
  `darabszam` int(11) NOT NULL,
  `ar` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- A tábla adatainak kiíratása `motor`
--

INSERT INTO `motor` (`id`, `leiras`, `motorkomponensek`, `darabszam`, `ar`) VALUES
(1, 'The main component of the engine that houses the cylinders and the pistons.', 'Cylinder Block', 6, 373000000),
(2, 'The component that moves up and down in the cylinders and generates power.', 'Pistons', 10, 22000000),
(3, 'The rods that connect the pistons to the crankshaft and transmit the power generated by the engine.', 'Connecting rods', 8, 1000000),
(4, 'The component that converts the up-and-down motion of the pistons into a rotary motion that can be transmitted to the gearbox.', 'Crankshaft', 8, 11000000),
(5, 'The shafts that operate the valves, which control the intake and exhaust of air and fuel in the engine.', 'Camshafts', 6, 7000000),
(6, 'The components that allow air and fuel into the engine and exhaust gases out of the engine.', 'Valves', 20, 3000000),
(7, 'A device that compresses air to increase the power output of the engine.', 'Turbocharger', 6, 1000000000),
(8, 'A component that cools the compressed air from the turbocharger before it enters the engine.', 'Intercooler', 4, 7000000),
(9, 'The components that inject fuel into the engine\'s cylinders.', 'Fuel injectors', 12, 1100000),
(10, 'A system that ignites the air and fuel mixture in the cylinders to produce power.', 'Ignition system', 4, 13000000),
(11, 'A system that removes exhaust gases from the engine.', 'Exhaust system', 6, 7000000),
(12, 'Various sensors and control units that monitor and optimize the engine\'s performance.', 'Sensors and control units', 8, 5000000);

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `motor`
--
ALTER TABLE `motor`
  ADD PRIMARY KEY (`id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `motor`
--
ALTER TABLE `motor`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
